### 결제 취소 test
POST http://localhost:10421/payment/cancel?orderNumber=B20000000011
Content-Type: application/json
X-User-ID:1

{
  "paymentKey": "tviva20251203172029n3Pl5",
  "cancelReason": "test"
}


### Snowflake 기반 주문 번호 생성
GET http://localhost:10421/hello