### 결제 취소 test
POST http://localhost:10421/payment/cancel?orderNumber=B20000000011
Content-Type: application/json
X-User-ID:1

{
  "paymentKey": "tviva20251203172029n3Pl5",
  "cancelReason": "test"
}


### 주문 준비
POST http://localhost:10421/orders/prepare
Content-Type: application/json
X-User-ID: 6

{
  "bookItems": [
    {"bookId": 16004,
    "quantity": 1
    }
  ]
}

### 임시 주문 생성
POST http://localhost:10421/orders
Content-Type: application/json
X-User-ID: 6

{
  "orderItems": [
    {"bookId" : 16004,
      "quantity" : 1,
      "isWrapped" : false,
      "wrappingPaperId" : null
    }
  ],
  "deliveryAddress":
    {
      "deliveryAddress": "주소1",
      "deliveryAddressDetail": "상세주소1",
      "deliveryMessage": "메세지",
      "recipient" : "수령인",
      "recipientPhoneNumber" : "01012345678"
    },
  "deliveryPolicyId" : 1,
  "wantDeliveryDate" : "2025-12-18",
  "couponId" : null,
  "point": null
}

### 배송비 정책 생성
POST http://localhost:10421/admin/delivery-policies
Content-Type: application/json

{
  "deliveryPolicyName": "택배",
  "deliveryFee": 3000,
  "freeDeliveryThreshold": 15000
}

### 비회원 주문 생성
POST http://localhost:10421/guest/orders
X-Guest-ID: test
Content-Type: application/json

{
  "guestName": "guestTest",
  "guestPhoneNumber": "01012345678",
  "guestPassword": "test1234!",
  "orderItems": [
    {
      "bookId": 2,
      "quantity": 2,
      "isWrapped": false,
      "wrappingPaperId": null
    }
  ],
  "deliveryAddress": {
    "deliveryAddress": "test",
    "deliveryAddressDetail": "detailTest",
    "deliveryMessage": "아무대나",
    "recipient": "guestTest",
    "recipientPhoneNumber": "01012345678"
  },
  "deliveryPolicyId": 1,
  "wantDeliveryDate": "2025-12-31"
}


### 회원 주문 준비 데이터 요청
GET http://localhost:10421/orders/B2-623596838912
X-User-ID: 16
Content-Type: application/json

{
  "bookItems": [
    {
      "bookId": 2,
      "quantity": 2
    },
    {
      "bookId": 3,
      "quantity": 1
    }
  ]
}

###
PATCH http://localhost:10421/orders/B2-623143854080/cancel
X-User-ID: 16